name: "S3 Sync"
description: "Sync a directory to an AWS S3 repository (orig: jakejarvis)"
author: tomaszopala (copy)
runs:
  using: docker
  image: Dockerfile
branding:
  icon: refresh-cw
  color: green
